const W=["周一","周二","周三","周四","周五","周六","周日"];
const P=["1-2节","3-4节","5-6节","7-8节","9-10节"];
const T=["08:30–10:05","10:25–12:00","14:30–16:05","16:25–18:00","19:00–20:35"];
const CLASS_COLORS=["#F39C3D","#F05D8C","#4F7DF3","#22B07D","#6F5CF6"];
const COURSE_COLORS=["#22B07D","#8A63F7","#4F7DF3"];
const R=D.map((r,i)=>({i,week:r[0],date:r[1],wd:r[2],pi:r[3],ci:r[4],group:r[5],li:r[6],oi:r[7],ni:r[8],course:C[r[4]],cls:L[r[6]],loc:O[r[7]],note:r[8]>=0?N[r[8]]:"",classColor:CLASS_COLORS[r[6]],courseColor:COURSE_COLORS[r[4]],period:P[r[3]],time:T[r[3]],weekday:W[r[2]],hours:2}));
const state={screen:"schedule",week:1,day:0};
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,"0");
function localDateKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function fmtDate(d){const x=new Date(d+"T00:00:00");return `${pad(x.getMonth()+1)}/${pad(x.getDate())}`}
function weekStart(w){return new Date(2026,7,31+(w-1)*7)}
function weekRange(w){const s=weekStart(w),e=new Date(s);e.setDate(s.getDate()+6);return `${pad(s.getMonth()+1)}/${pad(s.getDate())}–${pad(e.getMonth()+1)}/${pad(e.getDate())}`}
function weekDate(w,wd){const d=weekStart(w);d.setDate(d.getDate()+wd);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function currentWeek(){const s=new Date(2026,7,31),n=new Date(),w=Math.floor((new Date(n.getFullYear(),n.getMonth(),n.getDate())-s)/604800000)+1;return Math.max(1,Math.min(16,w))}
function sortRows(a){return [...a].sort((x,y)=>x.date.localeCompare(y.date)||x.pi-y.pi||x.ci-y.ci||x.li-y.li)}
function weekRows(w){return R.filter(r=>r.week===w)}
function courseTag(r){return `<span class="sheet-tag"><i class="dot" style="background:${r.courseColor};margin-top:0"></i>${r.course}</span>`}
function classTag(r){return `<span class="sheet-tag"><i class="dot" style="background:${r.classColor};margin-top:0"></i>${r.cls}</span>`}
function periodIndexNow(){const n=new Date(),m=n.getHours()*60+n.getMinutes();if(m<=605)return 0;if(m<=720)return 1;if(m<=965)return 2;if(m<=1080)return 3;return 4}
function nextRow(){const tk=localDateKey(),pi=periodIndexNow();return sortRows(R).find(r=>r.date>tk||(r.date===tk&&r.pi>=pi))||null}
function nextStatusText(r){if(!r)return "学期课程已结束";const today=new Date(),td=new Date(today.getFullYear(),today.getMonth(),today.getDate()),rd=new Date(r.date+"T00:00:00"),days=Math.round((rd-td)/86400000);if(days===0)return "今天";if(days===1)return "明天";return `${days}天后`}
function openLesson(i){const r=R[i];if(!r)return;$("sheetTags").innerHTML=`<div class="tag-row">${courseTag(r)}${classTag(r)}</div>`;$("sheetCourse").textContent=r.course;$("sheetClass").textContent=r.cls;$("sheetDate").textContent=`${r.date} · ${r.weekday} · 第${r.week}周`;$("sheetPeriod").textContent=`${r.period}（${r.time}）`;$("sheetLocation").textContent=r.loc;$("sheetGroup").textContent=r.group;$("sheetNote").textContent=r.note||"—";$("lessonMask").style.display="flex";$("lessonMask").setAttribute("aria-hidden","false")}
function closeMask(id){$(id).style.display="none";$(id).setAttribute("aria-hidden","true")}
function renderHeader(){const n=new Date();$("todayText").textContent=`${n.getFullYear()}年${n.getMonth()+1}月${n.getDate()}日`;$("weekChipText").textContent=`第${state.week}周`}
function renderFocus(){const r=nextRow();$("nextStatus").textContent=nextStatusText(r);if(!r){$("nextLesson").innerHTML=`<div class="empty-focus">当前没有后续课程记录。</div>`;return}$("nextLesson").innerHTML=`<div class="next-main" data-idx="${r.i}"><div class="next-course">${r.course}</div><div class="next-meta">${r.date} · ${r.weekday} · ${r.period}<br>${r.loc}</div><span class="next-class">${r.cls} · 教学班 ${r.group}</span></div>`}
function renderDateRail(){const rows=weekRows(state.week);$("weekRangeText").textContent=weekRange(state.week);$("weekSummary").textContent=`${rows.length*2} 课时`;let html="";W.forEach((wd,i)=>{const date=weekDate(state.week,i),items=rows.filter(r=>r.wd===i),day=Number(date.slice(8,10)),first=items[0];html+=`<button class="date-cell ${items.length?"has-class":""} ${state.day===i?"active":""}" data-day="${i}" style="--class-color:${first?first.classColor:"#4F7DF3"}" type="button"><span class="wd">${wd.replace("周","")}</span><span class="day">${day}</span><span class="count"></span></button>`});$("dateRail").innerHTML=html}
function renderAgenda(){const date=weekDate(state.week,state.day),rows=sortRows(R.filter(r=>r.week===state.week&&r.wd===state.day));const isToday=date===localDateKey();$("dayTitle").textContent=isToday?"今天课程":`${W[state.day]}课程`;$("daySubtitle").textContent=`${date} · ${rows.length*2}课时`;if(!rows.length){$("dayAgenda").innerHTML=`<div class="empty-card">这一天没有课程</div>`;return}$("dayAgenda").innerHTML=rows.map(r=>`<article class="lesson-card" data-idx="${r.i}" style="--class-color:${r.classColor}"><div class="time-col"><b>${r.period}</b><span>${r.time}</span></div><div class="lesson-info"><h3>${r.course}</h3><div class="class-line">${r.cls}</div><div class="loc">${r.loc}</div><div class="lesson-tags"><span class="mini-tag">教学班 ${r.group}</span>${r.note?`<span class="mini-tag">${r.note}</span>`:""}</div></div></article>`).join("")}
function renderWeekOverview(){const rows=weekRows(state.week);let html="";W.forEach((wd,i)=>{const a=sortRows(rows.filter(r=>r.wd===i));if(!a.length)return;html+=`<section class="day-group" data-day="${i}"><div class="day-group-head"><b>${wd} · ${fmtDate(a[0].date)}</b><span>${a.length*2}课时</span></div>${a.map(r=>`<div class="compact-lesson" data-idx="${r.i}" style="--class-color:${r.classColor}"><div class="p">${r.period}</div><div class="n">${r.course}<div class="subline">${r.loc}</div></div><span class="c">${r.cls}</span></div>`).join("")}</section>`});$("weekOverview").innerHTML=html||`<div class="empty-card">本周没有课程</div>`}
function renderSchedule(){renderHeader();renderFocus();renderDateRail();renderAgenda();renderWeekOverview()}
function renderStats(){const data=Array.from({length:16},(_,i)=>{const a=weekRows(i+1);return{w:i+1,h:a.length*2}}),max=Math.max(...data.map(x=>x.h),1);$("statWeekHours").textContent=`${weekRows(state.week).length*2}h`;$("weekChart").innerHTML=data.map(x=>`<button class="week-bar-item ${x.w===state.week?"active":""}" data-week="${x.w}" type="button"><span class="week-bar-space"><span class="week-bar" style="height:${Math.max(18,Math.round(x.h/max*112))}px"><span>${x.h}</span></span></span><span class="week-bar-label">W${x.w}</span></button>`).join("");$("classLoad").innerHTML=L.map((name,li)=>{const a=R.filter(r=>r.li===li),h=a.length*2,target=li===2?60:52,p=Math.min(100,h/target*100);return`<article class="load-card" data-class="${li}"><div class="load-top"><div class="name-with-dot"><i class="dot" style="background:${CLASS_COLORS[li]}"></i><div><h3>${name}</h3><div class="subline">${a.length}次课</div></div></div><div class="hours">${h}/${target}h</div></div><div class="track"><div class="fill" style="width:${p}%;background:${CLASS_COLORS[li]}"></div></div><div class="load-foot"><span>课时进度</span><span>${Math.round(p)}%</span></div></article>`}).join("");$("courseLoad").innerHTML=C.map((name,ci)=>{const a=R.filter(r=>r.ci===ci),h=a.length*2,p=h/268*100;return`<article class="course-card"><div class="course-top"><div class="name-with-dot"><i class="dot" style="background:${COURSE_COLORS[ci]}"></i><div><h3>${name}</h3><div class="subline">${a.length}次课 · 占总课时${p.toFixed(1)}%</div></div></div><div class="hours">${h}h</div></div><div class="track"><div class="fill" style="width:${p}%;background:${COURSE_COLORS[ci]}"></div></div></article>`}).join("")}
function renderFilters(){if($("weekFilter").options.length===1)$("weekFilter").innerHTML='<option value="all">全部周次</option>'+Array.from({length:16},(_,i)=>`<option value="${i+1}">第${i+1}周</option>`).join("");if($("classFilter").options.length===1)$("classFilter").innerHTML='<option value="all">全部班级</option>'+L.map((x,i)=>`<option value="${i}">${x}</option>`).join("");if($("courseFilter").options.length===1)$("courseFilter").innerHTML='<option value="all">全部课程</option>'+C.map((x,i)=>`<option value="${i}">${x}</option>`).join("")}
function renderAll(){renderFilters();const w=$("weekFilter").value,cl=$("classFilter").value,co=$("courseFilter").value,k=$("keyword").value.trim().toLowerCase();const a=sortRows(R.filter(r=>(w==="all"||r.week==w)&&(cl==="all"||r.li==cl)&&(co==="all"||r.ci==co)&&(!k||[r.course,r.cls,r.loc,r.group,r.note].join(" ").toLowerCase().includes(k))));$("resultCount").textContent=`${a.length} 条`;$("allList").innerHTML=a.length?a.map(r=>`<article class="all-item" data-idx="${r.i}" style="--class-color:${r.classColor}"><div class="all-item-top"><h3>${r.course}</h3><span class="date">${r.date} · ${r.weekday}</span></div><div class="meta">${r.period}（${r.time}）<br>${r.loc} · 教学班 ${r.group}</div><span class="class">${r.cls}</span></article>`).join(""):`<div class="empty-card">没有匹配课程</div>`}
function renderWeekPicker(){$("weekGridPicker").innerHTML=Array.from({length:16},(_,i)=>{const w=i+1;return`<button class="week-pick ${w===state.week?"active":""} ${w===currentWeek()?"current":""}" data-pick-week="${w}" type="button"><b>${w}</b><small>${weekRange(w)}</small></button>`}).join("")}
function setScreen(screen){state.screen=screen;document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));$("screen-"+screen).classList.remove("hidden");document.querySelectorAll(".tab-item").forEach(x=>x.classList.toggle("active",x.dataset.screen===screen));if(screen==="schedule")renderSchedule();if(screen==="stats")renderStats();if(screen==="all")renderAll();window.scrollTo({top:0,behavior:"smooth"})}
function chooseWeek(w){state.week=Math.max(1,Math.min(16,w));const todayW=currentWeek();if(state.week===todayW){const today=new Date().getDay();state.day=today===0?6:today-1}else state.day=(weekRows(state.week)[0]||{wd:0}).wd;closeMask("weekMask");setScreen("schedule")}
document.addEventListener("click",e=>{const tab=e.target.closest("[data-screen]");if(tab){setScreen(tab.dataset.screen);return}const day=e.target.closest("[data-day]");if(day){state.day=+day.dataset.day;renderDateRail();renderAgenda();return}const item=e.target.closest("[data-idx]");if(item){openLesson(+item.dataset.idx);return}const wb=e.target.closest("[data-week]");if(wb){chooseWeek(+wb.dataset.week);return}const wp=e.target.closest("[data-pick-week]");if(wp){chooseWeek(+wp.dataset.pickWeek);return}const classCard=e.target.closest("[data-class]");if(classCard){setScreen("all");$("classFilter").value=classCard.dataset.class;renderAll();return}});
$("goTodayBtn").onclick=()=>{state.week=currentWeek();const d=new Date().getDay();state.day=d===0?6:d-1;renderSchedule()};
$("weekPickerBtn").onclick=()=>{renderWeekPicker();$("weekMask").style.display="flex";$("weekMask").setAttribute("aria-hidden","false")};
$("lessonClose").onclick=()=>closeMask("lessonMask");$("weekClose").onclick=()=>closeMask("weekMask");$("lessonMask").onclick=e=>{if(e.target===$("lessonMask"))closeMask("lessonMask")};$("weekMask").onclick=e=>{if(e.target===$("weekMask"))closeMask("weekMask")};
["weekFilter","classFilter","courseFilter"].forEach(id=>$(id).onchange=renderAll);$("keyword").oninput=renderAll;
state.week=currentWeek();{const d=new Date().getDay();state.day=d===0?6:d-1}renderSchedule();renderWeekPicker();
if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js");
