const W=["周一","周二","周三","周四","周五","周六","周日"],P=["1–2节","3–4节","5–6节","7–8节","9–10节"];
const COLORS=["#17a98c","#2768f5","#7b61e8"];
const termStart=new Date(2026,7,31);
let state={view:'today',week:2,day:1,classId:-1,courseId:-1,q:''};
function parseDate(s){const a=s.split('-').map(Number);return new Date(a[0],a[1]-1,a[2]);}
function dateKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}
function weekDate(w,di){return addDays(termStart,(w-1)*7+di);}
function fmtMD(d){return (d.getMonth()+1)+'/'+d.getDate();}
function fmtCN(d){return (d.getMonth()+1)+'月'+d.getDate()+'日';}
function calcCurrentWeek(){const t=new Date();const a=new Date(t.getFullYear(),t.getMonth(),t.getDate());return Math.max(1,Math.min(16,Math.floor((a-termStart)/604800000)+1));}
function calcCurrentDay(){const js=new Date().getDay();return js===0?6:js-1;}
function recObj(r){return {week:r[0],date:r[1],day:r[2],period:r[3],course:r[4],group:r[5],classId:r[6],loc:r[7],note:r[8]};}
const records=D.map(recObj);
function filtered(){return records.filter(r=>(state.classId<0||r.classId===state.classId)&&(state.courseId<0||r.course===state.courseId)&&(!state.q||[C[r.course],L[r.classId],O[r.loc],r.note>=0?N[r.note]:'',r.date].join(' ').toLowerCase().includes(state.q)));}
function weekRecords(w=state.week){return filtered().filter(r=>r.week===w);}
function dayRecords(w=state.week,d=state.day){return weekRecords(w).filter(r=>r.day===d).sort((a,b)=>a.period-b.period);}
function weekRange(w){return fmtMD(weekDate(w,0))+'–'+fmtMD(weekDate(w,6));}
function courseTagClass(i){return 'course-tag c'+i;}
function eventHTML(r,showDay=false){return `<div class="event"><div class="event-time">${showDay?W[r.day]+'<br>':''}${P[r.period]}</div><div class="rail c${r.course}"></div><div class="event-card"><div class="row"><b>${C[r.course]}</b><span class="${courseTagClass(r.course)}">${r.group}</span></div><div class="meta">${L[r.classId]}<br>${O[r.loc]}</div>${r.note>=0?`<div class="note">${N[r.note]}</div>`:''}</div></div>`;}
function renderHeader(){const now=new Date();todayLabel.textContent=fmtCN(now)+' · '+W[calcCurrentDay()];heroWeek.textContent='第'+state.week+'周';heroRange.textContent=weekRange(state.week);const wr=weekRecords();heroHours.textContent=wr.length*2;const pct=Math.min(100,Math.max(0,state.week/16*100));termProgress.style.width=pct+'%';progressText.textContent='学期进度 '+Math.round(pct)+'%';}
function renderWeekStrip(){weekStrip.innerHTML='';for(let d=0;d<7;d++){const date=weekDate(state.week,d),count=weekRecords().filter(r=>r.day===d).length;const b=document.createElement('button');b.type='button';b.className='daybtn'+(d===state.day?' selected':'')+(dateKey(date)===dateKey(new Date())?' today':'');b.innerHTML=`<span class="wd">${W[d].replace('周','')}</span><span class="num">${date.getDate()}</span><span class="dot">${count}</span>`;b.addEventListener('click',()=>{state.day=d;renderWeekStrip();renderToday();});weekStrip.appendChild(b);}}
function renderToday(){const a=dayRecords();daySummary.textContent=W[state.day]+' · '+a.length+'课次 · '+a.length*2+'课时';dayTimeline.innerHTML=a.length?a.map(r=>eventHTML(r)).join(''):'<div class="empty">当天没有常规课程</div>';renderNext();}
function renderNext(){const today=dateKey(new Date());const arr=filtered().filter(r=>r.date>=today).sort((a,b)=>a.date.localeCompare(b.date)||a.period-b.period);const r=arr[0];if(!r){nextClass.innerHTML='<div class="empty" style="grid-column:1/-1">本学期没有后续常规课程</div>';return}nextClass.innerHTML=`<div class="next-icon">${r.week}</div><div><h4>${C[r.course]}</h4><p>${L[r.classId]} · ${P[r.period]}<br>${O[r.loc]}</p></div><div class="next-date">${fmtCN(parseDate(r.date))}<br>${W[r.day]}</div>`;}
function renderWeek(){const a=weekRecords().sort((x,y)=>x.day-y.day||x.period-y.period);weekSummary.textContent='第'+state.week+'周 · '+a.length+'课次 · '+a.length*2+'课时';weekTimeline.innerHTML=(state.week===16?'<div class="special" style="margin:4px 0 10px"><b>UI综合实训周：</b>周一至周五1–6节为实训占用，7–8节可正常排课。</div>':'')+(a.length?a.map(r=>eventHTML(r,true)).join(''):'<div class="empty">本周没有常规课程</div>');kpiSessions.textContent=a.length;kpiCourses.textContent=new Set(a.map(r=>r.course)).size;kpiClasses.textContent=new Set(a.map(r=>r.classId)).size;renderWeekBars();}
function renderWeekBars(){const vals=[];for(let w=1;w<=16;w++)vals.push(filtered().filter(r=>r.week===w).length*2);const max=Math.max(...vals,2);weekBars.innerHTML='<div class="week-bars-grid">'+vals.map((v,i)=>`<button type="button" class="wbar ${i+1===calcCurrentWeek()?'current ':''}${i+1===state.week?'active':''}" data-w="${i+1}" aria-label="第${i+1}周 ${v}课时"><i style="height:${Math.max(3,v/max*100)}%"></i></button>`).join('')+'</div><div class="week-labels"><span>第1周</span><span>第6周</span><span>第11周</span><span>第16周</span></div>';weekBars.querySelectorAll('.wbar').forEach(b=>b.addEventListener('click',()=>{state.week=+b.dataset.w;state.day=0;renderAll();}));}
function renderTerm(){const all=filtered();const courseHours=C.map((_,i)=>all.filter(r=>r.course===i).length*2);const total=courseHours.reduce((a,b)=>a+b,0)||1;let acc=0,stops=[];courseHours.forEach((v,i)=>{const s=acc/total*100;acc+=v;const e=acc/total*100;stops.push(`${COLORS[i]} ${s}% ${e}%`);});document.querySelector('.donut').style.background='conic-gradient('+stops.join(',')+')';document.querySelector('.donut').setAttribute('data-total',total);courseLegend.innerHTML=courseHours.map((v,i)=>`<div><i style="background:${COLORS[i]}"></i><span>${C[i]}</span><b>${v}h</b></div>`).join('');const cls=L.map((name,i)=>({name,h:all.filter(r=>r.classId===i).length*2}));const mx=Math.max(...cls.map(x=>x.h),1);classBars.innerHTML='<div style="font-size:12px;font-weight:700;margin-bottom:6px">班级课时</div>'+cls.map(x=>`<div class="class-row"><span class="name">${x.name}</span><span class="track"><i style="width:${x.h/mx*100}%"></i></span><b>${x.h}h</b></div>`).join('');allSummary.textContent=all.length+'课次 · '+all.length*2+'课时';allList.innerHTML=all.sort((a,b)=>a.date.localeCompare(b.date)||a.period-b.period).map(r=>eventHTML(r,true)).join('');}
function switchView(v){state.view=v;document.querySelectorAll('.segment button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));todayView.classList.toggle('hidden',v!=='today');weekView.classList.toggle('hidden',v!=='week');termView.classList.toggle('hidden',v!=='term');if(v==='today')renderToday();if(v==='week')renderWeek();if(v==='term')renderTerm();}
function renderAll(){renderHeader();renderWeekStrip();if(state.view==='today')renderToday();if(state.view==='week')renderWeek();if(state.view==='term')renderTerm();filterSummary.textContent=(state.classId<0&&state.courseId<0&&!state.q)?'执行课表 · 268课时':'筛选结果 · '+filtered().length*2+'课时';}
function initFilters(){L.forEach((x,i)=>classFilter.insertAdjacentHTML('beforeend',`<option value="${i}">${x}</option>`));C.forEach((x,i)=>courseFilter.insertAdjacentHTML('beforeend',`<option value="${i}">${x}</option>`));classFilter.addEventListener('change',()=>{state.classId=+classFilter.value;renderAll();});courseFilter.addEventListener('change',()=>{state.courseId=+courseFilter.value;renderAll();});searchInput.addEventListener('input',()=>{state.q=searchInput.value.trim().toLowerCase();renderAll();});}
document.querySelectorAll('.segment button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
filterBtn.addEventListener('click',()=>filterBox.classList.toggle('open'));
state.week=calcCurrentWeek();state.day=calcCurrentDay();initFilters();renderAll();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});